=== J-Viola/PRI/Projekt/www/xml/playlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definition of simple elements -->
    <xs:element name="name" type="xs:string"/>
    <xs:element name="totallength">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="unit" type="xs:string" default="min"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Genre elements -->
    <xs:element name="genre">
        <xs:complexType>
            <xs:choice>
                <xs:element name="metal" type="xs:string"/>
                <xs:element name="rock" type="xs:string"/>
                <xs:element name="other" type="xs:string"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="album" type="albumType"/>
    <xs:element name="song" type="songType"/>

    <!-- Complex types -->
    <xs:complexType name="albumType">
        <xs:sequence>
            <xs:element name="details" type="detailsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="songType">
        <xs:sequence>
            <xs:element name="details" type="detailsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="detailsType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="spotify_link" type="xs:string" use="optional"/>
                <xs:attribute name="genre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="metal"/>
                            <xs:enumeration value="rock"/>
                            <xs:enumeration value="other"/>
                        </xs:restriction>
                    </xs:simpleType>
                    <xs:default value="other"/>
                </xs:attribute>
                <xs:attribute name="length" type="xs:string" default="min"/>
                <xs:attribute name="author" type="xs:string" default="string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Playlist element -->
    <xs:element name="playlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="totallength"/>
                <xs:element ref="genre" minOccurs="0"/>
                <xs:element ref="album"/>
                <xs:element ref="song" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="autor" type="xs:string" use="required"/>
            <xs:attribute name="rating" type="xs:string" fixed="1"/>
            <xs:attribute name="users_voted" type="xs:string" fixed="0"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== J-Viola/PRI/Projekt/www/xml/test/test_3_not_valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="playlist.xsd">
    <totallength unit="min">9</totallength>
    <genre type="metal">Metal</genre>
    <album name="Timebomb">
        <song>Timebomb</song>
    </album>
    <album name="Chaos">
        <song>Moshpit</song>
        <song>Rise Up</song>
    </album>
</playlist>

=== J-Viola/PRI/Projekt/www/xml/upload/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<playlist autor="John Doe" users_voted="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="playlist.xsd">
    <name>My Playlist</name>
    <totallength unit="min">120</totallength>
    <genre type="rock">Rock</genre>
    <album name="Greatest Hits">
        <song>Hit Song 1</song>
        <song>Hit Song 2</song>
    </album>
    <song>Single Song 1</song>
    <song>Single Song 2</song>
</playlist>

=== J-Viola/PRI/Projekt/www/xml/upload/test_1_valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="playlist.xsd">
    <name>Linkin Park</name>
    <totallength unit="min">12</totallength>
    <genre type="rock">Rock</genre>
    <album name="Hybrid Theory">
        <song>Forgotten</song>
        <song>In The End</song>
    </album>
    <album name="Meteora">
        <song>Hit The Floor</song>
        <song>Figure 09</song>
    </album>
</playlist>
